#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

export BROWSER=firefox
export EDITOR=nvim
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for JetBrains IDEs

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Autostart Apps
$HOME/.local/bin/eww daemon &
dunst --config $HOME/.config/dunst/dunstrc &
picom --experimental-backends --config $HOME/.config/picom/picom.conf &

# Start polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Set wallpaper
#hsetroot -fill "$HOME/Pictures/Pictures/Wallpapers/FuturisticCyberpunkThemed.png"
feh --bg-fill "$HOME/Pictures/Wallpapers/playing-robot.jpg"
# Hex Gang
# hsetroot -solid "#192022"

# Start polybar
sh $HOME/.config/polybar/launch.sh

# I hate mouse drift.
xset m 0 0

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor -d I II III IV V VI VII VIII IX

#rule Vivaldi-stable                 desktop=I
#rule firefox                        desktop=I
#rule alacritty                      desktop=II
#rule code                           desktop=III
#rule lunarclient                    desktop=IV state=tiled
#rule Lutris                         desktop=V state=floating
#rule google-chrome                  desktop=V
#rule Steam                          desktop=VI
#rule vbox                           desktop=VII
#rule discord                        desktop=VIII
#rule Teams                          desktop=IX
#rule spotify                        desktop=X
rule mpv                            state=floating
rule Viewnior                       state=floating

# bspc config external_rules_command  "$HOME/.config/bspwm/scripts/spotify_wmclass.sh"

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier             Mod4

config border_width                 5
config window_gap                   10

config top_padding                  40
config bottom_padding               0

config split_ratio                  0.62
config borderless_monocle           true
config gapless_monocle              true

# Yes, this is stolen from gk.
outer='0xd91438'   # outer
# inner1='0x151a1c'  # focused
inner1='0xd91438'  # focused
inner2='0xd91438'  # focused
#inner2='0x131718'  # normal

targets() {
 	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

draw() { chwb2 -I "$inner" -O "$outer" -i "4" -o "9" $* |:; }

initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
 	while read -r _; do
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets normal)"
    done
